### ISSUE TITLE
Expose revisions interface and functionality

### ISSUE THREAD

**Issue by helen** [10up/ads-txt#1]
The contents of ads.txt is stored in a custom post type, which gives us revisions for free. The revisions interface (manually accessible at `/wp-admin/revision.php?revision=X`) mostly "just works", but needs a few accommodations to make it work properly.

- [x]  A link from the settings screen
- [x]  "Return to editor" and title links on revisions screen should link to settings screen
- [x]  "Restore This Revision" should send you back to the settings screen and have that revision's contents loaded in the editor
- [x]  The title shouldn't be shown in the diff viewer, as it shouldn't change and isn't relevant

**Comment by adamsilverstein** [comment]
Oh 3.6 :) https://github.com/WordPress/wordpress-develop/commit/ac0d0d1dee71ddea4f860b792faa8b69b5d11a5a
