### ISSUE TITLE
Review required actions in settings.

### ISSUE THREAD

**Issue by peterwilsoncc** [10up/ads-txt#101]
### Describe the bug

Currently pull requests are unable to be merged by non-admins as two required actions are not reporting:

* Test PHP (5.6)
* Test PHP (7.3) 

It appears that these are actions that have been removed from the workflow but remain as required checks in the admin settings.

**Resolution** Remove legacy actions from repository settings

### Steps to Reproduce

1. Create a pull request
2. Request and receive an approval 
3. Observe the actions above have not reported
4. Observe a non-admin is unable to merge the repo
5. Send Jeff a direct message asking him to merge.

### Screenshots, screen recording, code snippet

![Screen Shot 2022-04-22 at 9 43 59 am](https://user-images.githubusercontent.com/519727/164568496-eecf6461-0c12-41c5-9570-23b29e2944b4.png)

### Environment information

N/A - GitHub config issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Updated, nice catch, confirmed no longer showing in https://github.com/10up/ads-txt/pull/100.
