### ISSUE TITLE
Bump WordPress and PHP minimums

### ISSUE THREAD

**Issue by vikrampm1** [10up/ads-txt#102]
Bump WP & PHP Minimums to the following
 
- [x] WordPress to 5.7
- [x] PHP to 7.4
- [ ] Remove any no-longer-needed conditional code for older version support.
- [ ] Take a look at adjusting our testing matrices, if applicable.
- [x] Bump the minimums in plugin documentation and header fields.

**Comment by peterwilsoncc** [comment]
Reopened to create follow up PR for readme.md.
