### ISSUE TITLE
PHP Compatibility Workflow doesn't require a matrix

### ISSUE THREAD

**Issue by peterwilsoncc** [10up/ads-txt#106]
### Describe the bug

As the PHP Compatibility checker uses a tokenizer to evaluate compatibility (as opposed to code execution), it can be run on a single version of PHP rather than as part of a matrix.

The test version can be listed as `7.4-` to test for compatibility with all supported versions of PHP.

This will require a change to the protected branch config to remove the redundant runs as required checks.

### Steps to Reproduce

N/A

### Screenshots, screen recording, code snippet

Docs: https://github.com/PHPCompatibility/PHPCompatibility#testversion-in-the-ruleset-versus-command-line

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sidsector9** [comment]
Related discussion on Slack - https://10up.slack.com/archives/C84M9AA06/p1648460113851159
