### ISSUE TITLE
Missing variables  OWNERDOMAIN and MANAGERDOMAIN 

### ISSUE THREAD

**Issue by tott** [10up/ads-txt#107]
### Is your enhancement related to a problem? Please describe.

https://iabtechlab.com/wp-content/uploads/2022/04/Ads.txt-1.1.pdf adds support for OWNERDOMAIN and MANAGERDOMAIN which are currently still throwing errors in the plugin and get reported as "Unrecognized variable"

It would be also good to add a filter to overwrite the default set if needed. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Noting that this should build on #75 in updating the plugin to the latest ads.txt spec standard.
