### ISSUE TITLE
Remove missing action from required workflows.

### ISSUE THREAD

**Issue by peterwilsoncc** [10up/ads-txt#109]
### Describe the bug

The workflow `E2E Tests (WP minimum, WordPress/WordPress#4.9) ` is currently set as a required action for merging pull requests.

As this action has been removed (replaced with `E2E Tests (WP minimum, WordPress/WordPress#5.7)`) the repo's settings need to be updated in order to allow merges.

### Steps to Reproduce

1. Visit https://github.com/10up/ads-txt/issues/107
2. Note the missing workflow is blocking merge `E2E Tests (WP minimum, WordPress/WordPress#4.9) `

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Removed from `develop` branch required check, now seeing the expected 5.7 min check only
