### ISSUE TITLE
Plugin not creating/managing ads.txt file at all

### ISSUE THREAD

**Issue by scottbuscemi** [10up/ads-txt#14]
I installed the plugin on a client site hosted on WP Engine and the plugin's core functionality of creating or managing the ads.txt file isn't working.

An ads.txt file already exists for the website. Loading up the plugin for the first time shows a blank textbox. Entering something in will save the changes on the page, but the ads.txt file won't change.

Deleting the ads.txt file on the server doesn't have any impact.

**Comment by jakemgold** [comment]
Can you try saving peramlinks? CC @helen

**Comment by scottbuscemi** [comment]
Just tried and it didn't fix it.

**Comment by jakemgold** [comment]
Strange - we didn't explicitly try WP Engine, but we did try a few test environments that worked. We'll be in touch.

**Comment by scottbuscemi** [comment]
I just tried with my Local by Flywheel environment on a fresh install, and it didn't work there either.

**Comment by jakemgold** [comment]
Very odd. We'll be in touch shortly.

**Comment by scottbuscemi** [comment]
Whoa whoa -- this is my fault for the misunderstanding. I just realized that the plugin is using WordPress to deliver a result of ads.txt and not actually editing a file called 'ads.txt' on the server.

It may be worth noting the difference in the description :) Also, it looks like if an ads.txt currently exists that it overrides what the plugin outputs. Having that in the description would be helpful too!

**Comment by jakemgold** [comment]
Wait - so to be clear, if you go to your siteurl/ads.txt, it *does* appear, correct? It does dynamically generate the file (just like WP dynamically generates your page and post URLs), not actually write to the server.

**Comment by scottbuscemi** [comment]
I thought it wasn't working on the fresh install because I wasn't seeing an ads.txt file get generated in the file system. However, it does indeed work when I go to /ads.txt in the browser.

On my live site, I thought that the system would automatically pull in the contents of my ads.txt file that already exists on the server and manage that file. Since the ads.txt file existed, anything I typed into the plugin interface wasn't showing up since the server is delivering the actual ads.txt file and not delivering the result through WP.

**Comment by jakemgold** [comment]
Right - I can see how we might clarify that. It's meant to generate / manage ads.txt, much like creating a post in WordPress doesn't actually *write* the folders / files for the post to the server or import a file at its dynamically generated URL.

In a future update, I think it makes sense to have the plugin look for a "real" ads.txt file and clarify that it would conflict.

How are you enjoying the plugin, other than that point of confusion?

**Comment by scottbuscemi** [comment]
Thanks! I couldn't enjoy the plugin as a result of that confusion, but I'm sure it'll work out great now. I'll report back if I have any other feature requests 👍

**Comment by jeckman** [comment]
Created #15  to clarify this in readme

**Comment by adamsilverstein** [comment]
Thanks @jeckman, hopefully that will help avoid this confusion in the future. Closing this as resolved @scottbuscemi - please let us know if you see any additional issues.
