### ISSUE TITLE
Detect an actual `/ads.txt` file

### ISSUE THREAD

**Issue by helen** [10up/ads-txt#16]
Coming out of #14, it seems like it would be helpful if the plugin detected an actual root-level `ads.txt` file and notified the user that the plugin can't/won't override or edit it. This probably only needs to show on the edit screen.

**Comment by helen** [comment]
@kkopenhaver @tomjn I'm going to bring the discussion about approach over here so it's documented in the issue for easier central reference, and leave the PR for code review only. I've recently added [contributing guidelines](https://github.com/10up/ads-txt/blob/develop/CONTRIBUTING.md#pull-requests) that document this, so don't worry, nothing's wrong :)

> How do you feel about using something like wp_remote_get (or vip_safe_wp_remote_get) to get the data at http://exampleurl.com/adx.txt and comparing it to what the plugin expects the output to be? If the output matches, then ads.txt is being served from the plugin. If it doesn't, then there's likely a file already in place.

> This call could be cached using transients to reduce the load on the server and would be accompanied by a Check Again link or something similar in the admin notice to re-perform this check if the user believes the file has been removed.

That's an interesting thought - sending a web request instead of a server `file_exists()` check. That would be easier to determine location, too. I guess there's a question of when we need to run that detection. Ideally it would be each time you go to edit I suppose, but maybe it only needs to happen the first time you open up that edit screen, especially if you add a Check Again link to the notice? I'm a little hesitant to make it run solely in JS because having a message like that pop up with a delay seems like it would be jarring, but I'm definitely open to thoughts about how that kind of edit flow pans out.

I agree with @tomjn that for VIP environments that can be bypassed entirely :)

**Comment by kkoppenhaver** [comment]
👋 

Didn't see the tag on this issue, so just getting back to this now. Just pushed up a hybrid approach that I think handles all the various concerns that have been raised on this:
  - Performs the initial check with PHP, so as not to have a flash of the notice
  - Adds a `Re-run this check` link, which uses Javascript to check if the conflict has been resolved
  - Exits before the check if in a VIP environment
