### ISSUE TITLE
Add granular capability

### ISSUE THREAD

**Issue by ethanclevenger91** [10up/ads-txt#28]
Currently this page is available to those who with the manage_options capability. I ran into a situation where I want to create a role that only allows a user to edit this setting (the client's ad company). They have no business editing other settings on the site, and I don't really care to serve as middleman.

So I propose adding a specific capability. PR incoming.

**Comment by jeffpaul** [comment]
@ethanclevenger91 thanks for the feedback and welcome to `ads-txt`, your input is greatly appreciated!  I've added this issue and your related PR (again, thanks!) to the 1.2 milestone, but note that we don't yet have an ETA on when that will be ready for release.
