### ISSUE TITLE
Filter ads.txt content

### ISSUE THREAD

**Issue by ethanclevenger91** [10up/ads-txt#35]
**Is your enhancement related to a problem? Please describe.**
We have a third-party ad company that updates their own ads.txt content fairly frequently. We'd like to be able to consume this in an automated fashion and add it to our own ads.txt managed via WP rather than manually update their records when needed.

**Describe the solution you'd like**
Add a filter to the returned content for ads.txt. Probably a dedicated filter.

The result would allow a user to do something like this:

```
add_filter( 'adstxt_content', function( $adstxt ) {
    return $adstxt . third_party_adstxt_via_api();
});
```

**Comment by jeffpaul** [comment]
Resolved by #36
