### ISSUE TITLE
WPCS updates

### ISSUE THREAD

**Issue by jeffpaul** [10up/ads-txt#37]
**Describe the bug**
The following WPCS issues were shared with me, let's look to tackle these in our upcoming 1.2.0 release.  If they're false positives, then let's make sure they're skipped.
- [ ] in ads-txt/ads-txt.php (line 26) Detected usage of a non-validated input variable: $_SERVER (WordPress.Security.ValidatedSanitizedInput.InputNotValidated)
- [ ] in ads-txt/ads-txt.php (line 26) Missing wp_unslash() before sanitization. WordPress.Security.ValidatedSanitizedInput.MissingUnslash

**Expected behavior**
WPCS passes with no errors.

**Screenshots**
n/a

**Additional context**
See summary, source, and full reports attached.
[Ads.txt - report-full.txt](https://github.com/10up/ads-txt/files/3580668/Ads.txt.-.report-full.txt)
[Ads.txt - report-source.txt](https://github.com/10up/ads-txt/files/3580669/Ads.txt.-.report-source.txt)
[Ads.txt - report-summary.txt](https://github.com/10up/ads-txt/files/3580670/Ads.txt.-.report-summary.txt)

**Comment by adamsilverstein** [comment]
Addressed these issues in https://github.com/10up/ads-txt/pull/38
