### ISSUE TITLE
Support `app-ads.txt` too

### ISSUE THREAD

**Issue by westi** [10up/ads-txt#40]
**Is your enhancement related to a problem? Please describe.**
The plugin doesn't support `app-ads.txt` but sometime people want to create that too

**Describe the solution you'd like**
Support `app-ads.txt`

**Designs**

**Describe alternatives you've considered**
Manually creating a file in htdocs :(

**Additional context**

**Comment by helen** [comment]
This makes sense - it sounds like the format spec and therefore validation should be the same as it is for `ads.txt`, but I'm having a bit of a hard time really understanding the [spec doc](https://iabtechlab.com/wp-content/uploads/2019/03/app-ads.txt-v1.0-final-.pdf). It would help me a lot to get this milestoned if I could get some help demonstrating what an example file would look like and what the format and verification patterns should be. Actually putting this in place doesn't seem like a huge lift, although I do wonder if there should be two separate submenu items for these or one submenu item with a switcher.

**Comment by p0mmy** [comment]
Just changing '/ads.txt' to '/app-ads.txt' in the main script does the job for me, and Google does accept it. Fortunately I only need the latter file and not the former. This hack needs to be redone for each release. It would be cooler if the plugin could support both files, without manual hacks.

**Comment by ivankruchkoff** [comment]
+1 for this feature.
