### ISSUE TITLE
Test against WP 5.3

### ISSUE THREAD

**Issue by jeffpaul** [10up/ads-txt#46]
**Is your enhancement related to a problem? Please describe.**
Now that [WordPress 5.3 is released](https://wordpress.org/news/2019/11/kirk/), we'll want to test Ads.txt Manager to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [x] test Ads.txt Manager on WP 5.3
- [x] open issues for any incompatibilities noted in testing
- [x] resolve issues identified in testing
- [x] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by helen** [comment]
I'll handle this in #45
