### ISSUE TITLE
save() method doesn't respect new custom capability

### ISSUE THREAD

**Issue by ethanclevenger91** [10up/ads-txt#50]
**Describe the bug**
In save.php, the `save()` function is checking for the `customize` capability. It should be checking against the new `edit_ads_txt` cap.

**Steps to Reproduce**
1. Create a new user role based on Subscriber
2. Assign `edit_ads_txt` cap to that role
3. Create a user with that role
4. Log in as said user
5. Attempt to edit ads.txt
6. admin-ajax call dies, Javascript error ensues

**Expected behavior**
User with `edit_ads_txt` role should be able to edit ads.txt settings.

**Environment information**
 - Device: Lenovo ThinkPad
 - OS: Win10
 - Browser and version: Firefox, 73.0.1
 - WordPress version: 5.3.2
 - <details><summary>Site Health Info:</summary>
   `
### wp-core ###

version: 5.3.2
site_language: en_US
user_language: en_US
timezone: America/Los_Angeles
permalink: /%postname%/
https_status: false
user_registration: 0
default_comment_status: closed
multisite: false
user_count: 288
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/vagrant/dev/collider
wordpress_size: loading...
uploads_path: /home/vagrant/dev/collider/wp-content/uploads
uploads_size: loading...
themes_path: /home/vagrant/dev/collider/wp-content/themes
themes_size: loading...
plugins_path: /home/vagrant/dev/collider/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (2) ###

db.php: true
object-cache.php: true

### wp-active-theme ###

name: Collider - Complex (collider-v3)
version: 3.0.0
author: Complex Media Inc.
author_website: http://complex.com
parent_theme: none
theme_features: menus, post-thumbnails, editor-style, automatic-feed-links, amp, html5, custom-background, twentyeleven_header_style, widgets
theme_path: /home/vagrant/dev/collider/wp-content/themes/collider-v3

### wp-themes-inactive (3) ###

Collider: version: V2, author: topLingo
Twenty Nineteen: version: 1.4, author: the WordPress team
Twenty Twenty: version: 1.1, author: the WordPress team

### wp-plugins-active (22) ###

ACF Repeater & Flexible Content Collapser: version: 1.2.3, author: Thomas Meyer
Ads.txt Manager: version: 1.2.0, author: 10up
Advanced Custom Fields PRO: version: 5.8.7, author: Elliot Condon (latest version: 5.8.8)
AMP: version: 1.4.2, author: AMP Project Contributors (latest version: 1.4.4)
AMP Query Monitor Compat: version: 0.1.0, author: Weston Ruter, Google
Classic Editor: version: 1.5, author: WordPress Contributors
Collider: version: 1.1.0, author: Sterner Stuff Design
Complex TV Embed: version: 1.3, author: Anthony Rivera
Debug Bar ElasticPress: version: 1.4, author: 10up
Disable Search: version: 1.7.2, author: Scott Reilly
ElasticPress: version: 3.3, author: 10up (latest version: 3.4)
Envira Gallery: version: 1.8.8, author: Envira Gallery Team
Fastly: author: (undefined), version: 1.2.11
Instant Articles for WP: version: 4.2.0, author: Automattic, Dekode, Facebook
Query Monitor: version: 3.5.2, author: John Blackbourn
Redis Object Cache: version: 1.5.6, author: Till Krüss
Regenerate Thumbnails: version: 3.1.2, author: Alex Mills (Viper007Bond) (latest version: 3.1.3)
WP Migrate DB Pro: version: 1.9.8, author: Delicious Brains (latest version: 1.9.9)
WP Offload Media: version: 2.3.2, author: Delicious Brains
WPtouch Pro: version: 3.0.6, author: BraveNewCode Inc.
Yoast SEO: version: 13.0, author: Team Yoast (latest version: 13.2)
Yoast SEO: News: version: 12.4.1, author: Team Yoast

### wp-plugins-inactive (10) ###

Debug Bar Actions and Filters Addon: version: 1.5.4, author: Subharanjan
Debug Bar List Script & Style Dependencies: version: 1.1, author: Per Soderlind
Infinite Scroll: version: 2.6.2, author: Beaver6813, dirkhaim, Paul Irish, benbalter, Glenn Nelson
Remote Ads.txt: version: 1.0.0, author: Sterner Stuff
Rollbar: version: 2.6.1, author: Rollbar
Two Factor: version: 0.5.1, author: Plugin Contributors
User Switching: version: 1.5.3, author: John Blackbourn & contributors (latest version: 1.5.4)
Wordfence Security: version: 7.4.5, author: Wordfence (latest version: 7.4.6)
WP Crontrol: version: 1.7.1, author: John Blackbourn & crontributors
WP to Twitter: version: 3.4.4, author: Joseph C Dolson

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 4
gd_version: 2.2.5
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 4.15.0-74-generic x86_64
httpd_software: nginx/1.15.8
php_version: 7.4.1 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 512M
max_input_time: 60
upload_max_size: 100M
php_post_max_size: 100M
curl_version: 7.58.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.4.12-MariaDB-1:10.4.12+maria~bionic-log
client_version: mysqlnd 7.4.1

### wp-constants ###

WP_HOME: http://collider.test
WP_SITEURL: http://collider.test
WP_CONTENT_DIR: /home/vagrant/dev/collider/wp-content
WP_PLUGIN_DIR: /home/vagrant/dev/collider/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: true
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`
   </details>

**Comment by jeffpaul** [comment]
Nice catch @ethanclevenger91, happy to get a PR through review if you're able to work one up!
