### ISSUE TITLE
sellers.json support

### ISSUE THREAD

**Issue by jeffpaul** [10up/ads-txt#66]
**Is your enhancement related to a problem? Please describe.**
As [originally reported on WordPress.org](https://wordpress.org/support/topic/sellers-json/), we should consider adding `sellers.json` support to the plugin.

**Describe the solution you'd like**

Review the sellers.json details from the IAB and consider if this is functionality that makes sense within the plugin, as a separate plugin, or something not worth further investigating.  If its worth in this plugin, then cool let's add as a major plugin release.  If its worth adding as a separate plugin, is that something we want to build/support?

**Designs**

TBD

**Describe alternatives you've considered**

n/a

**Additional context**

[Background on sellers.json](https://digiday.com/media/what-are-sellers-json/) as well as more [in-depth info from the IAB Tech Lab](https://iabtechlab.com/sellers-json/).

**Comment by RoeyHarari44** [comment]
@jeffpaul do you know how to add seller.json to wix sites?

**Comment by jeffpaul** [comment]
@RoeyHarari44 no, I would recommend asking them via https://support.wix.com

**Comment by dhanendran** [comment]
@jeffpaul I have looked into the `sellers.json` file specification and it looks promising. Below statements from [adtelligent](https://adtelligent.com/blog/ad-ops/sellers-json-short-guide/) gives a quick summary of `sellers.json` files usage/benefit.

> Ads.txt and app-ads.txt initiatives allow checking the publisher’s direct sellers only. But they do not verify intermediary sellers on the SSP or ad exchange side. So how the advertisers can rest assured that they purchase the publisher’s inventory from the authorized reseller? And how publishers can be confident that their traffic would not fall into fraudsters’ hands? Sellers.json and SupplyChain object solve this issue and verify all vendors who participate in the selling of a bid request.

I would consider adding the support for the `sellers.json` file in this plugin itself as the seller listed in this file needs to be authorized in the `ads.txt` file as well as stated by IAB.

> A published and accessible sellers.json file allows the identity of the final seller of a bid request to be discovered (assuming that they are ads.txt authorized).

Ref:
1. https://iabtechlab.com/sellers-json/
2. https://support.google.com/authorizedbuyers/answer/9895942
3. https://support.google.com/adsense/answer/9889911?hl=en
4. https://adtelligent.com/blog/ad-ops/sellers-json-short-guide/

**Comment by jeffpaul** [comment]
@dhanendran awesome, thanks for that research/info.  In that case it sounds like we should look for a graceful way to introduce that functionality into the plugin.  Did you have any immediate ideas/preferences on how that might work?

**Comment by dhanendran** [comment]
@jeffpaul This can work just like the `ads.txt` implementation.

1. A new settings page for `sellers.json`
2. CodeMirror input area for the JSON input
3. Auto pretty print JSON and validator
4. Validating required `sellers.json` properties as per [spec](https://iabtechlab.com/wp-content/uploads/2019/07/Sellers.json_Final.pdf)
5. We could save the data in the CPT `adstxt`, so we can use the revision feature as well

**Comment by jeffpaul** [comment]
I'll chat internally before determining if we should build this into the existing plugin or spin it out into its own/separate plugin.  Thanks for the research and help on this @dhanendran!

**Comment by jeffpaul** [comment]
Closing this as something that's been deemed as having little value for site owners.
