### ISSUE TITLE
Update plugin functionality to ads.txt Specification Version 1.1

### ISSUE THREAD

**Issue by jeffpaul** [10up/ads-txt#75]
**Is your enhancement related to a problem? Please describe.**
ads.txt Specification is now up to [Version 1.0.3](https://iabtechlab.com/wp-content/uploads/2021/03/ads.txt-1.0.3.pdf), we should look to update the plugin to any new features.

**Describe the solution you'd like**
- [ ] assess what's new in 1.0.3 and what needs to be added to the plugin
- [ ] add issue(s) for changes needed in the plugin
- [ ] fix/build what's needed
- [ ] :shipit: 

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by jeffpaul** [comment]
Noting that the [spec is now at v1.1](https://iabtechlab.com/ads.txt/) and worth assessing what additionally has changed/is new/deprecated that we should update in the plugin:
- [1.1 spec](https://iabtechlab.com/wp-content/uploads/2022/04/Ads.txt-1.1.pdf)
- [implementation guide](https://iabtechlab.com/wp-content/uploads/2022/04/Ads.txt-1.1-Implementation-Guide.pdf)

**Comment by csloisel** [comment]
@jeffpaul  As far as I can tell, we are already supporting the latest specs in the plugin. It seems that the new specs just add a few new variables, and they have already been added to the validator:

https://github.com/10up/ads-txt/commit/99bd139cbc343e91221d9570500d405806e5e565
https://github.com/10up/ads-txt/commit/760dc0f189dd16c48079bd85595deaf97d7f8e42

I can't find anything else that we need to add support for at this moment.
