### ISSUE TITLE
Linter: accept "no authorized advertising systems" placerholder as valid.

### ISSUE THREAD

**Issue by peterwilsoncc** [10up/ads-txt#78]
**Is your enhancement related to a problem? Please describe.**

The ads.txt specification recommends sites without authorised advertising sellers use the following placeholder:
```
placeholder.example.com, placeholder, DIRECT, placeholder
```

Currently the built in linting of the ads.txt file highlights that as an error.

![Screen Shot 2022-01-14 at 3 17 13 pm](https://user-images.githubusercontent.com/519727/149450710-6a7fd9f0-a910-43bc-bc02-a021bb460614.png)

**Describe the solution you'd like**

For sites using the placeholder text above as the only text in the file, accept the content as valid but warn it indicates there are no authorized resellers.

**Designs**

Hacked together mock-up that would need work.

![Screen Shot 2022-01-14 at 3 20 54 pm](https://user-images.githubusercontent.com/519727/149451008-3f0efee0-cf87-4bc7-8394-577dbc9cd4dc.png)

Note: color code changed to yellow as warning rather than an error.

**Describe alternatives you've considered**

I considered suppressing the error message altogether but decided a warning of no authorized sellers would be more appropriate given the most likely ads.txt use case.

**Comment by ankitrox** [comment]
Source: https://iabtechlab.com/wp-content/uploads/2021/03/ads.txt-1.0.3.pdf
Page7
Section: 3.2.1 FILES WITHOUT AUTHORIZED ADVERTISING SYSTEM RECORDS

**Comment by ankitrox** [comment]
@peterwilsoncc Thank you for the suggestions.

Tracking the 

I have made some changes as per suggestions, also changed the nature of warning for sequence.

<img width="762" alt="Screenshot 2023-07-14 at 6 09 11 PM" src="https://github.com/10up/ads-txt/assets/1442637/8eed6489-2b5d-446f-b745-b43f73e4e094">
<img width="750" alt="Screenshot 2023-07-14 at 6 09 28 PM" src="https://github.com/10up/ads-txt/assets/1442637/0e636b99-48bd-4fb8-b66e-14465d585a7e">

Please let me know if this looks fine.
