### ISSUE TITLE
Maintaining readme.txt contributor header.

### ISSUE THREAD

**Issue by peterwilsoncc** [10up/ads-txt#99]
### Is your enhancement related to a problem? Please describe.

At the time of writing, the contributor header in the WordPress.org readme file lists 10up, 10up, Helen Hou-Sandi, Adam Silverstein, and Jake Goldman. I'll soon be adding my username to the list in #98.

https://github.com/10up/ads-txt/blob/a52a2a5f8480bf4f0127ea1a2da74bf28f04bae6/readme.txt#L2

Given Helen and Adam are no longer actively maintaining the plugin, should they be removed from the list? 

**Pros**
* it's clearer who is currently involved in the plugin
* visitors to the plugin page on wordpress.org will not @ mention legacy maintainers in support requests
* should Adam or Helen comment in the support forum, they will not have [maintainer badges](https://developer.wordpress.org/plugins/wordpress-org/special-user-roles-capabilities/#contributor)

**Cons**
* it demotes recognition of their earlier work setting up this plugin to the changelog
* the plugin is removed from their WP.org profiles

@helen, @adamsilverstein: as this change would affect you directly, I'd be interested in your thoughts.

### Describe alternatives you've considered

Two options for clarifying the current maintainers vs legacy maintainers

* retain Helen and Adam in `contributors` header and add a current maintainers section to the readme
* Remove Helen and Adam in `contributors` header but add maintainers section listing active and former maintainers.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by helen** [comment]
Doesn't bother me given how it's actually used in practice, by all means take me off :)

**Comment by jeffpaul** [comment]
My initial reaction is to keep folks listed there to recognize their historical efforts.  Should someone want to be removed (likely to avoid those @mentions for support), then I'd be fine with that as well.

**Comment by adamsilverstein** [comment]
no strong preference either way, whatever works best for you!

**Comment by jeffpaul** [comment]
@peterwilsoncc care to make a note about our default approach on handling this in https://10up.github.io/Open-Source-Best-Practices/maintaining/#maintainers-contributors?  I'd say something along the lines of "inactive contributors will only be removed at their request, we otherwise keep them listed as continued thanks for their historical efforts".  Also fine to add something about including those listed as Maintainers in CREDITS. as Contributors in readme.txt.
